name: Build & Publish TEST pypi

on: workflow_dispatch

jobs:

  build_binary:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
       os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Build wheels
        uses: henryiii/cibuildwheel@henryiii/fix/installcwd
        env:
          CIBW_SKIP: pp*
          CIBW_ARCHS_LINUX: auto aarch64
          CIBW_ARCHS_MACOS: x86_64 arm64 universal2
          CIBW_BEFORE_BUILD: python -c "import shutil ; shutil.copyfile('tools/setup-pypi.cfg','setup.cfg')"
          CIBW_BEFORE_TEST: python -c "import os ; os.remove('setup.cfg')"
          CIBW_TEST_COMMAND: python -m apsw.tests -v
          APSW_HEAVY_DURATION: 2
          APSW_TEST_FSYNC_OFF: set

      - uses: actions/upload-artifact@v3
        with:
          name: wheelhouse
          path: ./wheelhouse/*.whl


  build_source:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install --upgrade pip

    - name: Create source dist
      run: python setup.py sdist --for-pypi

    - uses: actions/upload-artifact@v3
      with:
        name: wheelhouse
        path: ./dist/*

  pypi_publish:
    needs: [build_source, build_binary]
    runs-on: ubuntu-latest
    permissions:
        id-token: write
    steps:
    - name: Stage wheels
      uses: actions/download-artifact@v3
      with:
        name: wheelhouse
        path: wheelhouse

    - run: |
        mkdir -p dist
        mv -v wheelhouse/* dist/
        ls -l dist/

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
       repository_url: https://test.pypi.org/legacy/

